### ISSUE TITLE
RFC: Optional Chaining

### ISSUE THREAD

**Issue by solomon-b** [hasura/kriti-lang#30]
RFC Is in PR #29

Please use this space to discuss the RFC.

[rendered](https://github.com/hasura/kriti-lang/blob/RFC/optional-chaining/RFCs/OptionalChaining.md)

Also, does anyone have good formats for RFC issues and PRs we can adopt?

**Comment by solomon-b** [comment]
This RFC doesn't address array syntax for optional lookups yet.

**Comment by kolharsam** [comment]
Hey @solomon-b! This seems like a great idea! 

I just had this question, and this may not be directly related to the RFC, but it arose from seeing a conditional listed in the RFC:

https://github.com/hasura/kriti-lang/pull/29/files#diff-ac274d55acb124dbd6cc47dcbc92043d60465b78900f044ecbb81c9ffbc10462R57

The `if` condition listed here would fail with an error if the value of `$body?.bar.baz` turns out to be `null` or `undefined`. I assume that this would be the case based on the `current` code in the parser. Is that an okay behaviour to have?

**Comment by solomon-b** [comment]
Hi @kolharsam! Yes that looks like a typo. It should be:
```
runKriti "{{ if $body?.bar.baz /= null }} {{ $body.bar.baz}} {{ else }} null {{ end }}" [($body, {"foo": 1})]
```
